### ISSUE TITLE
[BUG] - After starting the geogig server it is not possible manipulate the repositories in command line.

### ISSUE THREAD

**Issue by jlanio** [locationtech/geogig#309] opened 2017-05-10 21:15 UTC
After some testing I noticed a pattern in the error.
The exception always occurs when starting `geogig serve --multirepo` and then accesses the repository address: `http://localhost:8182/repos/demo`.

Then if you try to do any `shp import, add or commit` operation the error will be returned: 

> Exception in thread "main" java.lang.RuntimeException: org.rocksdb.RocksDBException:
at com.google.common.base.Throwables.propagate(Throwables.java:160)
at org.locationtech.geogig.rocksdb.RocksConnectionManager.connect(RocksConnectionManager.java:121)
at ........

_However if we finish the process responsible for the server, everything returns to normal._

![a](https://cloud.githubusercontent.com/assets/10765588/25921504/47ed3ebe-359b-11e7-8933-a0653a981e15.jpg)

Am I doing something wrong? Or it really is a bug!
#302

**Comment by emerkle826** [comment] 2017-05-17 16:38
@jlanio After looking into this a bit more, I believe the issue is that you are using ``geogig serve`` for a RocksDB backed repo, and while that process is running, trying to use the CLI on the same repo. You can't do that with RocksDB backed repositories as the RocksDB libraries lock the database. Once the ``serve`` command starts, that process will put a lock on the database and you won't be able to run any other process that tries to access it, including an instance of the CLI.

I'm going to leave this ticket open however, and re-purpose it to give a better message when this situation occurs.

**Comment by jlanio** [comment] 2017-05-19 13:50
@emerkle826 Actually, I understand that this behavior is desirable to preserve the actual data. However will not it be necessary only when command repository changes are sent (POST)?

Actually it is necessary to block commits made via the command line while I am accessing the logs of a certain repository or I make comparisons between commit via web with geogig serves??

**Comment by groldan** [comment] 2017-06-27 16:55
So, just to clarify things: if you're serving a file (rocksdb) repository through the WEB API, the server will have it open in read-write mode. Rocksdb allows opening in read-write mode by a single OS process at a time.
Yet, you can still run any read-only command through the CLI, just not anything that would change the repository.
That said, there was a bug that prevented running read only commands through the CLI in that situation, which was fixed by #340, so it'll be fixed in 1.1.1 or you can grab the latest nightly from http://ares.boundlessgeo.com/geogig/1.1.x/geogig-1.1.x-latest.zip

**Closed by groldan** 2017-06-27 16:55 UTC
