### ISSUE TITLE
Clone of large repositories into RocksDB fails on Windows

### ISSUE THREAD

**Issue by emerkle826** [locationtech/geogig#302] opened 2017-05-03 16:48 UTC
Issue initially reported via the geogig-devel mailing list:

> Hi,
> I am using Geogig 1.0 on Windows 7, Oracle JRE 1.8.0_121. I have a remote repository served via Geoserver/PostGIS, containing approx 1GB of data for Antarctica.
> 
> From the documentation, I think I should be able to clone the remote repository into a directory on the local machine. I tried to do this first by issuing the command:
> 
> geogig.bat clone http://<servername>/geoserver/geogig/repos/master master
> 
> in the intended directory. I get the following output:
> 
> Cloning into 'master'...
> 
> Fetching objects from refs/heads/master
> 
> 10:55:42.835 [main] ERROR o.locationtech.geogig.cli.GeogigCLI - An unhandled error occurred: org.rocksdb.RocksDBException: ▒. See the log for more details.
> java.lang.RuntimeException: org.rocksdb.RocksDBException: ▒
> at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-18.0.jar:na]
> at org.locationtech.geogig.rocksdb.RocksdbObjectStore.putAll(RocksdbObjectStore.java:382) ~[geogig-rocksdb-1.0.jar:1.0]
> at org.locationtech.geogig.storage.impl.ForwardingObjectDatabase.putAll(ForwardingObjectDatabase.java:162) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.di.ObjectDatabasePutInterceptor$GraphUpdatingObjectDatabase.putAll(ObjectDatabasePutInterceptor.java:98) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.storage.impl.ForwardingObjectDatabase.putAll(ForwardingObjectDatabase.java:162) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.remote.BinaryPackedObjects.ingest(BinaryPackedObjects.java:224) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.remote.HttpRemoteRepo.fetchMoreData(HttpRemoteRepo.java:456) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.remote.HttpRemoteRepo.fetchNewData(HttpRemoteRepo.java:208) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.porcelain.FetchOp._call(FetchOp.java:257) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.porcelain.FetchOp._call(FetchOp.java:48) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:153) ~[geogig-api-1.0.jar:1.0]
> at org.locationtech.geogig.porcelain.CloneOp._call(CloneOp.java:163) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.porcelain.CloneOp._call(CloneOp.java:39) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:153) ~[geogig-api-1.0.jar:1.0]
> at org.locationtech.geogig.cli.porcelain.Clone.runInternal(Clone.java:164) ~[geogig-cli-1.0.jar:1.0]
> at org.locationtech.geogig.cli.AbstractCommand.run(AbstractCommand.java:68) ~[geogig-cli-1.0.jar:1.0]
> at org.locationtech.geogig.cli.GeogigCLI.executeInternal(GeogigCLI.java:528) ~[geogig-cli-1.0.jar:1.0]
> at org.locationtech.geogig.cli.GeogigCLI.execute(GeogigCLI.java:367) ~[geogig-cli-1.0.jar:1.0]
> at org.locationtech.geogig.cli.app.CLI.main(CLI.java:80) [geogig-cli-app-1.0.jar:1.0]
> Caused by: org.rocksdb.RocksDBException: ▒
> at org.rocksdb.RocksDB.write0(Native Method) ~[rocksdbjni-4.13.4.jar:na]
> at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[rocksdbjni-4.13.4.jar:na]
> at org.locationtech.geogig.rocksdb.RocksdbObjectStore.putAll(RocksdbObjectStore.java:371) ~[geogig-rocksdb-1.0.jar:1.0]
> 
> ... 17 common frames omitted
> 
> An unhandled error occurred: org.rocksdb.RocksDBException: ▒. See the log for more details.
> 
> The error happens consistently after fetching around 300,000 objects (out of about 1,130,000). The logfile gives no extra information over what’s pasted above.
> 
> I have tried:
> 
> geogig.bat init
> 
> in the directory as well, in case it was missing an initialised empty repo, but get the same response. With identical software versions on a Centos 7 Linux Virtual Box VM on the same Windows box, I get:
> 
> geogig clone http://<servername>/geoserver/geogig/repos/master master
> 
> Cloning into 'master'...
> 
> Fetching objects from refs/heads/master
> 
> 1,129,655
> 
> Processed 1,129,697 objects. Inserted: 1,129,697. Existing: 0. Time: 21.46 min. Compressed size: 630,289,302 bytes. Uncompressed size: 1,257,346,509 bytes.
> 
> 100%
> 
> Done.
> 
> The created local repo is as expected. It looks like I might have hit some size or complexity limit in the Windows case? It looks like I am using rocksdb 4.13.4.

**Comment by emerkle826** [comment] 2017-05-03 16:50
I asked David to replace the RocksDB jar (4.13.4) with a slightly older version (4.11.2) to see if the error messages generated were more informative and got this:

> Thanks for your input. I replaced the rocksdb jar with 4.11.2 and repeated the clone – I now get:
> 
> Fetching objects from refs/heads/master
> 
> 17:12:32.171 [main] ERROR o.locationtech.geogig.cli.GeogigCLI - An unhandled error occurred: org.rocksdb.RocksDBException: IO error: Failed to FlushViewOfFile: C:\Users\DARB1.BS-DARB1-L5\Documents\projects\add\data\working\master\.geogig\objects.rocksdb/000015.sst: The process cannot access the file because another process has locked a portion of the file.
> 
> . See the log for more details.
> 
> java.lang.RuntimeException: org.rocksdb.RocksDBException: IO error: Failed to FlushViewOfFile: C:\Users\DARB1.BS-DARB1-L5\Documents\projects\add\data\working\master\.geogig\objects.rocksdb/000015.sst: The process cannot access the file because another process has locked a portion of the file.
> at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-18.0.jar:na]
> at org.locationtech.geogig.rocksdb.RocksdbObjectStore.putAll(RocksdbObjectStore.java:382) ~[geogig-rocksdb-1.0.jar:1.0]
> at org.locationtech.geogig.storage.impl.ForwardingObjectDatabase.putAll(ForwardingObjectDatabase.java:162) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.di.ObjectDatabasePutInterceptor$GraphUpdatingObjectDatabase.putAll(ObjectDatabasePutInterceptor.java:98) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.storage.impl.ForwardingObjectDatabase.putAll(ForwardingObjectDatabase.java:162) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.remote.BinaryPackedObjects.ingest(BinaryPackedObjects.java:224) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.remote.HttpRemoteRepo.fetchMoreData(HttpRemoteRepo.java:456) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.remote.HttpRemoteRepo.fetchNewData(HttpRemoteRepo.java:208) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.porcelain.FetchOp._call(FetchOp.java:257) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.porcelain.FetchOp._call(FetchOp.java:48) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:153) ~[geogig-api-1.0.jar:1.0]
> at org.locationtech.geogig.porcelain.CloneOp._call(CloneOp.java:163) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.porcelain.CloneOp._call(CloneOp.java:39) ~[geogig-core-1.0.jar:1.0]
> at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:153) ~[geogig-api-1.0.jar:1.0]
> at org.locationtech.geogig.cli.porcelain.Clone.runInternal(Clone.java:164) ~[geogig-cli-1.0.jar:1.0]
> at org.locationtech.geogig.cli.AbstractCommand.run(AbstractCommand.java:68) ~[geogig-cli-1.0.jar:1.0]
> at org.locationtech.geogig.cli.GeogigCLI.executeInternal(GeogigCLI.java:528) ~[geogig-cli-1.0.jar:1.0]
> at org.locationtech.geogig.cli.GeogigCLI.execute(GeogigCLI.java:367) ~[geogig-cli-1.0.jar:1.0]
> at org.locationtech.geogig.cli.app.CLI.main(CLI.java:80) [geogig-cli-app-1.0.jar:1.0]
> Caused by: org.rocksdb.RocksDBException: IO error: Failed to FlushViewOfFile: C:\Users\DARB1.BS-DARB1-L5\Documents\projects\add\data\working\master\.geogig\objects.rocksdb/000015.sst: The process cannot access the file because another process has locked a portion of the file.
> at org.rocksdb.RocksDB.write0(Native Method) ~[rocksdbjni-4.11.2.jar:na]
> at org.rocksdb.RocksDB.write(RocksDB.java:555) ~[rocksdbjni-4.11.2.jar:na]
> at org.locationtech.geogig.rocksdb.RocksdbObjectStore.putAll(RocksdbObjectStore.java:371) ~[geogig-rocksdb-1.0.jar:1.0]
> 
> ... 17 common frames omitted
> 
> An unhandled error occurred: org.rocksdb.RocksDBException: IO error: Failed to FlushViewOfFile: C:\Users\DARB1.BS-DARB1-L5\Documents\projects\add\data\working\master\.geogig\objects.rocksdb/000015.sst: The process cannot access the file because another process has locked a portion of the file.
> 
> . See the log for more details.
> 
> The log contains nothing more than this, apart from three occurrences of:
> 
> 2017-05-03 17:17:07,712 INFO [main] o.l.g.p.CreateDeduplicator [CreateDeduplicator.java:40] No DeduplicationService service found, using default heap based one
> 
> Before the stacktrace. I guess this new error reveals it’s some kind of file locking issue.
> 
> Thanks,
> David.

**Comment by emerkle826** [comment] 2017-05-03 20:12
I am able to reproduce this issue locally with a Windows 7 64-bit VM, attempting to clone a repo with almost 1.2 million features. Cloning from a repository with only about 5,000 features doesn't seem to have any issues though.

**Comment by emerkle826** [comment] 2017-05-03 20:27
There seems to also be a related issue when attempting to commit a large number of feature adds to a RocksDB backed repository on Windows. Attempting to do a `geogig shp import buildingsm.shp`, where `buildingsm.shp` is a Shapefile with about 1.2 million features, works. Following that with a `geogig add` works. But when trying to commit with `geogig commit -m "initial commit"` errors out with a similar exception:

With RocksDB 4.11.2 library:
> 
> C:\Users\boundless\Desktop\buildingsm>g:\bin\geogig commit -m "initial commit"
> An unhandled error occurred: org.rocksdb.RocksDBException: IO error: Failed to FlushViewOfFile: C:\Users\boundless\Desktop\buildingsm\.geogig\objects.rocksdb/000026.sst: The process cannot access the file because another process has locked a portion of the file.
> . See the log for more details.

With RocksDB 4.13.4 library:

> 
> C:\Users\boundless\Desktop\buildingsm>g:\bin\geogig commit -m "initial commit"
> An unhandled error occurred: org.rocksdb.RocksDBException: ?. See the log for more details.

**Comment by jlanio** [comment] 2017-05-10 14:12
Hello @emerkle826 , I have a problem that is perhaps similar. Any idea what's going on?

> Exception in thread "main" java.lang.RuntimeException: org.rocksdb.RocksDBException:
        at com.google.common.base.Throwables.propagate(Throwables.java:160)
        at org.locationtech.geogig.rocksdb.RocksConnectionManager.connect(RocksConnectionManager.java:121)
        at org.locationtech.geogig.rocksdb.RocksConnectionManager.connect(RocksConnectionManager.java:34)
        at org.locationtech.geogig.storage.impl.ConnectionManager.acquire(ConnectionManager.java:61)
        at org.locationtech.geogig.rocksdb.RocksdbObjectStore.open(RocksdbObjectStore.java:88)
        at org.locationtech.geogig.rocksdb.RocksdbObjectDatabase.open(RocksdbObjectDatabase.java:70)
        at org.locationtech.geogig.storage.impl.ForwardingObjectDatabase.open(ForwardingObjectDatabase.java:40)
        at org.locationtech.geogig.storage.impl.ForwardingObjectDatabase.open(ForwardingObjectDatabase.java:40)
        at org.locationtech.geogig.repository.impl.RepositoryImpl.open(RepositoryImpl.java:116)
        at org.locationtech.geogig.repository.impl.GeoGIG.getRepository(GeoGIG.java:124)
        at org.locationtech.geogig.cli.GeogigCLI.newGeoGIG(GeogigCLI.java:268)
        at org.locationtech.geogig.cli.GeogigCLI.loadRepository(GeogigCLI.java:240)
        at org.locationtech.geogig.cli.GeogigCLI.loadRepository(GeogigCLI.java:235)
        at org.locationtech.geogig.cli.GeogigCLI.getGeogig(GeogigCLI.java:180)
        at org.locationtech.geogig.cli.app.CLI.main(CLI.java:46)
Caused by: org.rocksdb.RocksDBException:
        at org.rocksdb.RocksDB.open(Native Method)
        at org.rocksdb.RocksDB.open(RocksDB.java:286)
        at org.locationtech.geogig.rocksdb.RocksConnectionManager.connect(RocksConnectionManager.java:104)
        ... 13 more

**Comment by emerkle826** [comment] 2017-05-10 14:32
@jlanio unfortunately with the 4.13.4 version of the RocksDB library, the exception message is cryptic, if there's anything at all in the message. If you temporarily downgrade the library to 4.11.2, and retry the operation, the message will likely give more details. In the cases I've run into, this type of exception is usually associated with an internal lock on the RocksDB database file(s).

I'm not sure what operation you are attempting when you see the error. If it's not a clone operation, please open another GitHub issue with any details about the operation you are performing when the error happens, the OS you are running, and any other details about the data/repositories you are working with (how many features, how large the dataset is, etc).

As for this issue, the team is aware and we are working on it.

**Comment by jlanio** [comment] 2017-05-10 14:54
@emerkle826 , Thanks for listening. 
After some testing I noticed a pattern in the error.
The exception always occurs when starting `geogig serve --multirepo` and then accesses the repository address:` http://localhost:8182/repos/demo.`

Then if you try to do any `shp import, add or commit` operation the error will be returned.

Is there really a need to open issue with more details on?
Or simply I'm not working correctly with the tool, before the operation` shp import, add or commit` finalize the `geogig serve`

**Comment by emerkle826** [comment] 2017-05-10 15:34
@jlanio Thanks for the details. However, what you are describing seems like an issue with the `serve` command, not the `clone` operation. Let's keep the discussion in this GitHub issue to the `clone` bug above.

As for the issues you are having, it would be better to capture them in a separate GitHub issue, or send an email to the [geogig-mailing-list](mailto:geogig-dev@locationtech.org) with the details.

**Comment by groldan** [comment] 2017-06-27 16:57
This issue is fixed by #333, to be released with 1.1.1

**Closed by groldan** 2017-06-27 16:57 UTC
Labels: bug
